name: System tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_call' && github.run_id || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' }}

jobs:
  end-to-end:
    name: Start e2e tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      STAGE_CHAIKA_SOFT_URL: ${{ secrets.STAGE_CHAIKA_SOFT_URL }}
      STAGE_ZITADEL_TOKEN: ${{ secrets.STAGE_ZITADEL_TOKEN }}
      STAGE_ZITADEL_URL: ${{ secrets.STAGE_ZITADEL_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-android-gradle

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run E2E tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :e2e-tests:connectedAndroidTest -i

      - name: Upload E2E reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports
          path: |
            e2e-tests/build/reports
            e2e-tests/build/outputs/androidTest-results
            app/build/reports/androidTests
            app/build/outputs/androidTest-results
          if-no-files-found: ignore
          retention-days: 7
